spring:
  autoconfigure:
    exclude:
     - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
     - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #spring 定时任务多节点配置
  task:
    scheduling:
      pool:
        size: 10
logging:
  config: classpath:logback/logback-spring-dev.xml
